{{- if .Values.connectivityLink.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.connectivityLink.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  labels:
    app.kubernetes.io/part-of: openshift-ai-ref
    app.kubernetes.io/managed-by: Helm
{{- end }}
