{{- if .Values.connectivityLink.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: openshift-default
  annotations:
    argocd.argoproj.io/sync-wave: "45"
    argocd.argoproj.io/sync-options: SkipDryRun=true
  labels:
    app.kubernetes.io/part-of: openshift-ai-ref
    app.kubernetes.io/managed-by: Helm
spec:
  controllerName: openshift.io/gateway-controller/v1
---
apiVersion: kuadrant.io/v1beta1
kind: Kuadrant
metadata:
  name: kuadrant
  namespace: {{ .Values.connectivityLink.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "45"
    argocd.argoproj.io/sync-options: SkipDryRun=true
  labels:
    app.kubernetes.io/part-of: openshift-ai-ref
    app.kubernetes.io/managed-by: Helm
{{- end }}
